version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - SEP4_NETWORK

  user-service:
    build:
      context: .
    container_name: user-service
    restart: unless-stopped
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - SEP4_NETWORK
    depends_on:
      - db

volumes:
  postgres-data:

networks:
  SEP4_NETWORK:
    external: true
