version: '3.8'

services:
  user-service:
    build:
      context: .
    container_name: user-service
    ports:
      - "5001:80"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - SEP4_NETWORK
    restart: unless-stopped

networks:
  SEP4_NETWORK:
    external: true
